baseURL = "https://grassro0t.github.io/"
title = "我的技术博客"
theme = "PaperMod"
locale = "zh-cn"
paginate = 10
enableRobotsTXT = true

[params]
  author = "GrassRo0t"
  defaultTheme = "auto" # auto/dark/light
  ShowReadingTime = true
  ShowWordCount = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true # 代码块复制按钮 ✨程序员必备
  UseHugoToc = true          # 文章目录
  homeInfoParams = { Title = "欢迎", Content = "技术笔记博客" }

[permalinks]
posts = "/posts/:slug/" # 文章url格式，类似hexo